apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: user9-dotnet-app-
spec:
  params:
    - name: GIT_URL
      value: "https://github.com/LiranMizrahi/dotnet-app.git"
    - name: REGISTRY
      value: liranmizrahi
    - name: IMAGE_NAME
      value: dotnet-app
    - name: IMAGE_TAG
      value: v20
    - value: user9-application
  pipelineRef:
    name: user9-dotnet-app
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: storage
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Mi
          volumeMode: Filesystem
